### ISSUE TITLE
Проверка ДЗ React

### ISSUE THREAD

**Issue by AlexeyErshov999** [Mairo07/Filmopoisk#2]
## Review

### Базовые требования:

| Критерий                                                                                          |   Макс.   | Моя оценка |
|---------------------------------------------------------------------------------------------------|:---------:|:----------:|
| Создан github-репозиторий, в нём есть README, gitignore, установлены все необходимые зависимости  | 5 баллов. |     5     |
| Проект запускается                                                                                | 5 баллов. |     5     |
| Вёрстка соответствует дизайн-макетам (допускаются минимальные отхождения, адаптив не требуется)   | 5 баллов. |     5     |

#### Шапка (max 2 балла)

| Критерий                      |  Макс.   | Моя оценка |
|-------------------------------|:--------:|:----------:|
| Позиционируется липко (стики) | 2 балла. |      2     |

#### Авторизация (max 16 баллов)

| Критерий                                                                                            |  Макс.   | Моя оценка |
|-----------------------------------------------------------------------------------------------------|:--------:|:----------:|
| Для реализации модального окна используется портал                                                  | 3 балла. |     3      |
| После успешной авторизации кнопка «Войти» меняется на заглушку иконки пользователя и кнопку «Выйти» | 2 балла. |     2      |
| Сохраняем авторизационный токен из ответа ручки бэка (например, в localStorage)                     | 4 балла. |     4      |
| В идеале, работать с токеном через thunk (где-то в мидлваре)                                        | 3 балла. |     3      |
| По клику на кнопку «Выйти» удаляем токен и снимает авторизацию                                      | 2 балла. |     2      |
| При инициализации приложения проверяем авторизационный токен                                        | 2 балла. |     2      |

#### Поиск:
| Критерий                                                                      |  Макс.   | Моя оценка |
|-------------------------------------------------------------------------------|:--------:|:----------:|
| Поиск происходит во время ввода пользователем символов. Дёргаем ручку /search | 4 балла. |     4      |

#### Фильтры:
| Критерий                               |  Макс.   | Моя оценка |
|----------------------------------------|:--------:|:----------:|
| Реализованы фильтры с dropdown         | 4 балла. |     4      |
| Сохранять фильтры в query-params       | 3 балла. |     3      |
| Реализован список фильмов с пагинацией | 3 балла. |     1      |
Список фильмов есть, пагинации нет - 1 балл

#### Реализована работа с получением данных:
| Критерий                          |  Макс.   | Моя оценка |
|-----------------------------------|:--------:|:----------:|
| Дёргаем ручку /movie              | 4 балла. |     4      |
| Соответствующие данные отрисованы | 3 балла. |     3      |

#### Возможность поставить оценку:
| Критерий                                                                          |  Макс.   | Моя оценка |
|-----------------------------------------------------------------------------------|:--------:|:----------:|
| Есть запрос за получением оценки для фильма                                       | 3 балла. |     0      |
| Если пользователь авторизован, даём возможность поставить оценку - запрос мутации | 3 балла. |     0      |
| После выставления оценки обновляем кеш запроса /movie                             | 4 балла. |     0      |

### Общий функционал (max 8 баллов)
| Критерий                                                   |  Макс.   | Моя оценка |
|------------------------------------------------------------|:--------:|:----------:|
| Реализовать единообразную обработку ошибок для запросов    | 2 балла. |     0      |
| Реализован лоадер                                          | 2 балла. |     1      | Во время загрузки отображается надпись "isLoading..." - поставлю балл
| Используем debounce для поиска фильма и выставления оценки | 4 балла. |     0      |

### Стор (max 8 баллов)

| Критерий                                                                            |  Макс.   | Моя оценка |
|-------------------------------------------------------------------------------------|:--------:|:----------:|
| Используется rtk и rtk-query                                                        | 4 балла. |     4      |
| Данные корректно разбиты на модули (пример - авторизация, searchParams из фильтров) | 2 балла. |      2     |
| Селекторы написаны оптимально (нет кучи дублирования)                               | 2 балла. |      2     |

### Миграция на Next (max 20 баллов)
| Критерий                                                                                    |   Макс.    | Моя оценка |
|---------------------------------------------------------------------------------------------|:----------:|:----------:|
| Реализована миграция с использованием SSR                                                   | 14 баллов. |      0     |
| Для картинок используется Image некста. Скрины фильма, которые вне вьюпорта грузятся лениво |  2 балла.  |      0     |
| Страница фильма реализована с помощью Dynamic Routes                                        |  4 балла.  |      0     |

### Ограничения:
- [ ] Новая функциональность, добавленная после дедлайна, не учитывается. Допустимы минорные доработки в уже существующую логику.
- [ ] Функциональность, реализованная с помощью запрещённых библиотек (готовый ui-kit), не учитывается.

> Набранная сумма `61 балл`

### Фидбэк
Отличная работа! Очень многие не успели сделать все, поэтому ты проделала огромную работу!<br>
По вопросам и замечаниям к ревью пиши в тг: @AleBro9999

**Comment by AlexeyErshov999** [comment]
Почему то не отобразившийся комментарий)
Во время загрузки отображается надпись "isLoading..." - поставлю балл

**Comment by Mairo07** [comment]
Спасибо за ревью!)
